services:
  - type: web
    name: sm-payroll-backend
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      - key: REFRESH_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false
